print("-" * 30)
print("         REGRA DE 3      ")
print("-" * 30)
print("         a ------ b")
print("         X ------ c")
print()
print()
a = float(input("Digite o valor para A: "))
b = float(input("Digite o valor para B: "))
c = float(input("Digite o valor para C: "))
print()
print("Resultado", float(a * c) / b)
