print("-" * 30)
print("         REGRA DE 3      ")
print("-" * 30)
print("         a ------ b")
print("         X ------ c")
print()
print()
a = int(input("Digite o valor para A: "))
b = int(input("Digite o valor para B: "))
c = int(input("Digite o valor para C: "))
print()
print("Resultado", int(a * c) / b)
